### PR TITLE
clippy: fix warnings

### PR DESCRIPTION
**Pull request by paolobarbolini**

### CODE REVIEW

**Comment by KillingSpark** [comment]
I'll have to check that none of the casts were actually important but most seem to be redundant.

Could you tell me how you called clippy to find these? It does not produce warning for them with just `cargo clippy`.

**Comment by paolobarbolini** [comment]
I denied those warnings, which are allowed by default, by adding that line in lib.rs which you can see in the PR

**Comment by KillingSpark** [comment]
Could you tell me how you called clippy to find these? It does not produce warning for them with just `cargo clippy`.

**Comment by KillingSpark** [comment]
And thanks for the contribution of course!

**Comment by KillingSpark** [comment]
> I denied those warnings, which are allowed by default, by adding that line in lib.rs which you can see in the PR

I see. I thought clippy told you to do that and I was a bit confused :)

**Pull request merged**
