### PR TITLE
Fixed small typos in comments and Readme

### PR DESCRIPTION
**Pull request by Riuqlav**
Fixed small typos in Comments and Readme

### CODE REVIEW

**Comment by KillingSpark** [comment]
Thanks! I don't imagine you actually proof-read all of this. Do you mind sharing what tool you used to check this? I might let it run over my other projects too :)

**Comment by Riuqlav** [comment]
I actually went through everything, I only use the extension code spell
checker, but without it the vscode alone does a little suggestions, you
just go and fix it

**Comment by KillingSpark** [comment]
Oh damn. Then extra thanks for the work!

**Comment by KillingSpark** [comment]
Hehe that actually broke a test that relied on that typo existing. Don't worry its already fixed just wanted to let you know :)

**Pull request merged**
